const RP_COLUMNS = {
  _id: 'ID',
  name: 'Name',
  siteBound: 'Site Bound',
  slopeAngle: 'Slope Angle',
  crepeAngle: 'Crepe Angle',
  volume: 'Volume',
  sizeX: 'Size X',
  sizeY: 'Size Y',
  sizeZ: 'Size Z',
  positionX: 'Position X',
  positionY: 'Position Y',
  positionZ: 'Position Z',
  rotationX: 'Rotation X',
  rotationY: 'Rotation Y',
  rotationZ: 'Rotation Z',
};

const RP_DISC_COLUMNS = {
  _id: 'ID',
  siteBound: 'Site Bound',
  name: 'Name',
  slopeAngle: 'Slope Angle',
  crepeAngle: 'Crepe Angle',
  volume: 'Volume',
  sizeX: 'Size X',
  sizeY: 'Size Y',
  sizeZ: 'Size Z',
  positionX: 'Position X',
  positionY: 'Position Y',
  positionZ: 'Position Z',
  rotationX: 'Rotation X',
  rotationY: 'Rotation Y',
  rotationZ: 'Rotation Z',
};

const SITE_COLUMNS = {
  _id: 'ID',
  name: 'Name',
  generateVirtual1DExtendedRPs: 'Generate Virtual 1D Extended RPs',
  calculateMaximumCuboids: 'Calculate Maximum Cuboids',
  calculatePolyhedrons: 'Calculate Polyhedrons',
  generateDiscontinuityPlanes: 'Generate Discontinuity Planes',
};

const GPR_COLUMNS = {
  _id: 'ID',
  siteId: 'Site ID',
  rectangleNumber: 'Rectangle Number',
  shape: 'Shape',
  longitudinalProfileNumber: 'Longitudinal Profile Number',
  traversalProfileNumber: 'Traversal Profile Number',
  distance: 'Distance',
  spacing: 'Spacing',
  dimension: 'Dimension',
  positionX: 'Position X',
  positionY: 'Position Y',
  positionZ: 'Position Z',
  antenna: 'Antenna',
  longitudinalProfilesDirectory: 'Longitudinal Profiles Directory',
  longitudinalProfilesMaxDepth: 'Longitudinal Profiles Max Depth',
  longitudinalProfilesMaxDistance: 'Longitudinal Profiles Max Distance',
  traversalProfilesDirectory: 'Traversal Profiles Directory',
  traversalProfilesMaxDepth: 'Traversal Profiles Max Depth',
  traversalProfilesMaxDistance: 'Traversal Profiles Max Distance',
  mapReferenceSystemForStartOfLongitudinalProfiles:
    'Map Reference System For Start Of Longitudinal Profiles',
  mapReferenceSystemForStartOfTransversalProfiles:
    'Map Reference System For Start Of Transversal Profiles',
  vertex1StartOfLongitudinalProfilesX:
    'Vertex 1 Start Of Longitudinal Profiles X',
  vertex1StartOfLongitudinalProfilesY:
    'Vertex 1 Start Of Longitudinal Profiles Y',
  vertex1StartOfLongitudinalProfilesZ:
    'Vertex 1 Start Of Longitudinal Profiles Z',
  vertex1EndOfLongitudinalProfilesX: 'Vertex 1 End Of Longitudinal Profiles X',
  vertex1EndOfLongitudinalProfilesY: 'Vertex 1 End Of Longitudinal Profiles Y',
  vertex1EndOfLongitudinalProfilesZ: 'Vertex 1 End Of Longitudinal Profiles Z',
  vertex1StartOfTraversalProfilesX: 'Vertex 1 Start Of Traversal Profiles X',
  vertex1StartOfTraversalProfilesY: 'Vertex 1 Start Of Traversal Profiles Y',
  vertex1StartOfTraversalProfilesZ: 'Vertex 1 Start Of Traversal Profiles Z',
  vertex1EndOfTraversalProfilesX: 'Vertex 1 End Of Traversal Profiles X',
  vertex1EndOfTraversalProfilesY: 'Vertex 1 End Of Traversal Profiles Y',
  vertex1EndOfTraversalProfilesZ: 'Vertex 1 End Of Traversal Profiles Z',
  vertex2StartOfLongitudinalProfilesX:
    'Vertex 2 Start Of Longitudinal Profiles X',
  vertex2StartOfLongitudinalProfilesY:
    'Vertex 2 Start Of Longitudinal Profiles Y',
  vertex2StartOfLongitudinalProfilesZ:
    'Vertex 2 Start Of Longitudinal Profiles Z',
  vertex2EndOfLongitudinalProfilesX: 'Vertex 2 End Of Longitudinal Profiles X',
  vertex2EndOfLongitudinalProfilesY: 'Vertex 2 End Of Longitudinal Profiles Y',
  vertex2EndOfLongitudinalProfilesZ: 'Vertex 2 End Of Longitudinal Profiles Z',
  vertex2StartOfTraversalProfilesX: 'Vertex 2 Start Of Traversal Profiles X',
  vertex2StartOfTraversalProfilesY: 'Vertex 2 Start Of Traversal Profiles Y',
  vertex2StartOfTraversalProfilesZ: 'Vertex 2 Start Of Traversal Profiles Z',
  vertex2EndOfTraversalProfilesX: 'Vertex 2 End Of Traversal Profiles X',
  vertex2EndOfTraversalProfilesY: 'Vertex 2 End Of Traversal Profiles Y',
  vertex2EndOfTraversalProfilesZ: 'Vertex 2 End Of Traversal Profiles Z',
  explanation: 'Explanation',
};

const GPR_DISC_COLUMNS = {
  siteId: 'Site ID',
  rectangleLineNumber: 'Rectangle Line Number',
  profileType: 'Profile Type',
  crackProfileNumber: 'Crack Profile Number',
  typeOfCrack: 'Type Of Crack',
  typeOfDisc: 'Type Of Disc',
  dip: 'Dip',
  dipDirection: 'Dip Direction',
  mapReferenceSystem: 'Map Reference System',
  startingVertexX: 'Starting Vertex X',
  startingVertexY: 'Starting Vertex Y',
  startingVertexZ: 'Starting Vertex Z',
  endVertexX: 'End Vertex X',
  endVertexY: 'End Vertex Y',
  endVertexZ: 'End Vertex Z',
  nX: 'N X',
  nY: 'N Y',
  nZ: 'N Z',
};

const GPR_PROFILE_COLUMNS = {
  siteId: 'Site ID',
  rectangleLineNumber: 'Rectangle Line Number',
  profileType: 'Profile Type',
  longitudinalProfileNumber: 'Longitudinal Profile Number',
  traversalProfileNumber: 'Traversal Profile Number',
  distance: 'Distance',
  spacing: 'Spacing',
  numberOfProfile: 'Number Of Profile',
  startingVertexX: 'Starting Vertex X',
  startingVertexY: 'Starting Vertex Y',
  startingVertexZ: 'Starting Vertex Z',
  endVertexX: 'End Vertex X',
  endVertexY: 'End Vertex Y',
  endVertexZ: 'End Vertex Z',
  frequency: 'Frequency',
  filname: 'Filname',
};

const JOINT_SET_COLUMNS = {
  siteId: 'Site ID',
  discontinuitySetId: 'Discontinuity Set ID',
  shape: 'Shape',
  type: 'Type',
  dip: 'Dip',
  dipDirection: 'Dip Direction',
  expectationTraceLength: 'Expectation Trace Length',
  frictionAngle: 'Friction Angle',
  location: 'Location',
  positionX: 'Position X',
  positionY: 'Position Y',
  positionZ: 'Position Z',
  trend: 'Trend',
  plunge: 'Plunge',
  vertex2X: 'Vertex 2 X',
  vertex2Y: 'Vertex 2 Y',
  vertex2Z: 'Vertex 2 Z',
  vertex3X: 'Vertex 3 X',
  vertex3Y: 'Vertex 3 Y',
  vertex3Z: 'Vertex 3 Z',
  vertex4X: 'Vertex 4 X',
  vertex4Y: 'Vertex 4 Y',
  vertex4Z: 'Vertex 4 Z',
};

const SCANLINE_COLUMNS = {
  siteId: 'Site ID',
  dip: 'Dip',
  dipDirection: 'Dip Direction',
  pX: 'P X',
  pY: 'P Y',
  pZ: 'P Z',
};

const LIDAR_JOINT_SET_COLUMNS = {
  siteId: 'Site ID',
  discontinuitySetId: 'Discontinuity Set ID',
  shape: 'Shape',
  dip: 'Dip',
  dipDirection: 'Dip Direction',
  expectationTraceLength: 'Expectation Trace Length',
  spacing: 'Spacing',
  fisherK: 'Fisher K',
  frictionAngle: 'Friction Angle',
  fractureIntensity: 'Fracture Intensity',
  positionX: 'Position X',
  positionY: 'Position Y',
  positionZ: 'Position Z',
  numberOfFracture: 'Number Of Fracture',
};

const LIDAR_POINT_CLOUD_COLUMNS = {
  siteId: 'Site ID',
  vertexId: 'Vertex ID',
  jointSetNumber: 'Joint Set Number',
  discontiunityPlaneNumber: 'Discontinuity Plane Number',
  positionX: 'Position X',
  positionY: 'Position Y',
  positionZ: 'Position Z',
};

const LIDAR_TRACES_COLUMNS = {
  siteId: 'Site ID',
  traceId: 'Trace ID',
  shape: 'Shape',
  dip: 'Dip',
  dipDirection: 'Dip Direction',
  persistence: 'Persistence',
  traceInitialVertexX: 'Trace Initial Vertex X',
  traceInitialVertexY: 'Trace Initial Vertex Y',
  traceInitialVertexZ: 'Trace Initial Vertex Z',
  traceEndingVertexX: 'Trace Ending Vertex X',
  traceEndingVertexY: 'Trace Ending Vertex Y',
  traceEndingVertexZ: 'Trace Ending Vertex Z',
};

module.exports = {
  RP_COLUMNS,
  RP_DISC_COLUMNS,
  SITE_COLUMNS,
  GPR_COLUMNS,
  GPR_DISC_COLUMNS,
  GPR_PROFILE_COLUMNS,
  JOINT_SET_COLUMNS,
  SCANLINE_COLUMNS,
  LIDAR_JOINT_SET_COLUMNS,
  LIDAR_POINT_CLOUD_COLUMNS,
  LIDAR_TRACES_COLUMNS,
};
