var mongoose = require('mongoose');
const LidarTrace = require('../models/lidarTrace.model');

const getBySiteId = async (siteId) => {
  const constSiteId = new mongoose.Types.ObjectId('65b356d89f5a66aefdce5ee8');
  await LidarTrace.insertMany([
    {
      siteId: constSiteId,
      traceId: 1,
      shape: 'linear',
      dip: 45,
      dipDirection: 90,
      persistence: 'persistent',
      traceInitialVertexX: 50,
      traceInitialVertexY: 100,
      traceInitialVertexZ: 30,
      traceEndingVertexX: 60,
      traceEndingVertexY: 110,
      traceEndingVertexZ: 35,
    },
    {
      siteId: constSiteId,
      traceId: 2,
      shape: 'curved',
      dip: 60,
      dipDirection: 180,
      persistence: 'intermittent',
      traceInitialVertexX: 70,
      traceInitialVertexY: 120,
      traceInitialVertexZ: 40,
      traceEndingVertexX: 80,
      traceEndingVertexY: 130,
      traceEndingVertexZ: 45,
    },
    {
      siteId: constSiteId,
      traceId: 3,
      shape: 'linear',
      dip: 40,
      dipDirection: 120,
      persistence: 'persistent',
      traceInitialVertexX: 55,
      traceInitialVertexY: 105,
      traceInitialVertexZ: 32,
      traceEndingVertexX: 65,
      traceEndingVertexY: 115,
      traceEndingVertexZ: 37,
    },
    {
      siteId: constSiteId,
      traceId: 4,
      shape: 'curved',
      dip: 50,
      dipDirection: 150,
      persistence: 'intermittent',
      traceInitialVertexX: 52.5,
      traceInitialVertexY: 102.5,
      traceInitialVertexZ: 31.5,
      traceEndingVertexX: 62.5,
      traceEndingVertexY: 112.5,
      traceEndingVertexZ: 36.5,
    },
    {
      siteId: constSiteId,
      traceId: 5,
      shape: 'linear',
      dip: 36,
      dipDirection: 100,
      persistence: 'persistent',
      traceInitialVertexX: 57.5,
      traceInitialVertexY: 107.5,
      traceInitialVertexZ: 33,
      traceEndingVertexX: 67.5,
      traceEndingVertexY: 117.5,
      traceEndingVertexZ: 38,
    },
    {
      siteId: constSiteId,
      traceId: 6,
      shape: 'curved',
      dip: 48,
      dipDirection: 130,
      persistence: 'intermittent',
      traceInitialVertexX: 60.5,
      traceInitialVertexY: 110.5,
      traceInitialVertexZ: 34,
      traceEndingVertexX: 70,
      traceEndingVertexY: 120,
      traceEndingVertexZ: 40,
    },
    {
      siteId: constSiteId,
      traceId: 7,
      shape: 'linear',
      dip: 38,
      dipDirection: 85,
      persistence: 'persistent',
      traceInitialVertexX: 65,
      traceInitialVertexY: 115,
      traceInitialVertexZ: 37,
      traceEndingVertexX: 75,
      traceEndingVertexY: 125,
      traceEndingVertexZ: 42,
    },
    {
      siteId: constSiteId,
      traceId: 8,
      shape: 'curved',
      dip: 55,
      dipDirection: 110,
      persistence: 'intermittent',
      traceInitialVertexX: 70,
      traceInitialVertexY: 120,
      traceInitialVertexZ: 40,
      traceEndingVertexX: 80,
      traceEndingVertexY: 130,
      traceEndingVertexZ: 45,
    },
    {
      siteId: constSiteId,
      traceId: 9,
      shape: 'linear',
      dip: 42,
      dipDirection: 95,
      persistence: 'persistent',
      traceInitialVertexX: 62.5,
      traceInitialVertexY: 112.5,
      traceInitialVertexZ: 36.5,
      traceEndingVertexX: 72.5,
      traceEndingVertexY: 122.5,
      traceEndingVertexZ: 41.5,
    },
    {
      siteId: constSiteId,
      traceId: 10,
      shape: 'curved',
      dip: 58,
      dipDirection: 125,
      persistence: 'intermittent',
      traceInitialVertexX: 67.5,
      traceInitialVertexY: 117.5,
      traceInitialVertexZ: 38,
      traceEndingVertexX: 77.5,
      traceEndingVertexY: 127.5,
      traceEndingVertexZ: 43.5,
    },
  ]);
  const lidarTraces = await LidarTrace.find({ siteId });
  if (lidarTraces) return lidarTraces;
  throw new Error('Lidar traces not found');
};

module.exports = {
  getBySiteId,
};
